<a href="https://colab.research.google.com/github/fabioaraujo/python-fun/blob/master/Sudoku_Solver.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
grid = [
        [8,0,0,0,0,0,0,0,0],
        [0,0,3,6,0,0,0,0,0],
        [0,7,0,0,9,0,2,0,0],
        [0,5,0,0,0,7,0,0,0],
        [0,0,0,0,4,5,7,0,0],
        [0,0,0,1,0,0,0,3,0],
        [0,0,1,0,0,0,0,6,8],
        [0,0,8,5,0,0,0,1,0],
        [0,9,0,0,0,0,4,0,0]
        ]

In [209]:
import numpy as np
print(np.matrix(grid))

[[8 0 0 0 0 0 0 0 0]
 [0 0 3 6 0 0 0 0 0]
 [0 7 0 0 9 0 2 0 0]
 [0 5 0 0 0 7 0 0 0]
 [0 0 0 0 4 5 7 0 0]
 [0 0 0 1 0 0 0 3 0]
 [0 0 1 0 0 0 0 6 8]
 [0 0 8 5 0 0 0 1 0]
 [0 9 0 0 0 0 4 0 0]]


In [0]:
def possible_number(x,y,n) :
  global grid
  #check line and column
  for i in range (0,9):
    if grid[x][i] == n :
      return False
    if grid[i][y] == n :
      return False

  #check which grid we are working on
  x_grid = (x//3) * 3
  y_grid = (y//3) * 3
  
  #check the grid if we already this n number in it
  for i in range(0,3):
    for j in range(0,3):
      if grid[x_grid+i][y_grid+j] == n:
        return False
  return True

In [211]:
# the line 0 has an 8 number
possible_number(0,1,8)

False

In [212]:
# the zero line, and column 1 and first grid doesn't has the number 1
possible_number(0,1,1)

True

In [213]:
# the first grid already has the number 8
possible_number(1,1,8)

False

In [0]:
def solve():
  for x in range (0,9):
    for y in range (0,9):
      #if the cell is blank try to find a possible number
      if grid[x][y] == 0:
        for n in range(1,10):
            if possible_number(x, y, n):
              #if possible number put it on the grid
              grid[x][y] = n
              #Check if more numbers are empty
              if solve():
                return True
              #if we have an empty number put a 0 in here and try to figure out the next number
              grid[x][y] = 0
        #We have an empty number
        return False
  #Found out a solution
  return True



In [215]:
solve()
print(np.matrix(grid))

[[ True]]
[[8 1 2 7 5 3 6 4 9]
 [9 4 3 6 8 2 1 7 5]
 [6 7 5 4 9 1 2 8 3]
 [1 5 4 2 3 7 8 9 6]
 [3 6 9 8 4 5 7 2 1]
 [2 8 7 1 6 9 5 3 4]
 [5 2 1 9 7 4 3 6 8]
 [4 3 8 5 2 6 9 1 7]
 [7 9 6 3 1 8 4 5 2]]


In [0]:
grid = [
        [0,0,0,0,0,0,0,0,0],
        [0,0,0,0,0,0,0,0,0],
        [0,0,0,0,0,0,0,0,0],
        [3,8,4,0,0,0,0,0,0],
        [0,0,0,0,0,0,0,0,0],
        [0,0,0,0,0,0,0,0,0],
        [0,0,0,0,0,0,0,0,0],
        [0,0,0,0,0,0,0,0,0],
        [0,0,0,0,0,0,0,0,2]
        ]

In [217]:
solve()
print(np.matrix(grid))

[[ True]]
[[1 2 3 4 5 6 7 8 9]
 [4 5 6 7 8 9 1 2 3]
 [7 9 8 1 2 3 4 5 6]
 [3 8 4 2 1 5 6 9 7]
 [2 1 5 6 9 7 3 4 8]
 [6 7 9 3 4 8 2 1 5]
 [5 3 1 8 6 2 9 7 4]
 [8 6 2 9 7 4 5 3 1]
 [9 4 7 5 3 1 8 6 2]]


In [0]:
grid = [
        [5,3,0,0,7,0,0,0,0],
        [6,0,0,1,9,5,0,0,0],
        [0,9,8,0,0,0,0,6,0],
        [8,0,0,0,6,0,0,0,3],
        [4,0,0,8,0,3,0,0,1],
        [7,0,0,0,2,0,0,0,6],
        [0,6,0,0,0,0,2,8,0],
        [0,0,0,4,1,9,0,0,5],
        [0,0,0,0,8,0,0,7,9]
        ]

In [219]:
solve()
print(np.matrix(grid))

[[ True]]
[[5 3 4 6 7 8 9 1 2]
 [6 7 2 1 9 5 3 4 8]
 [1 9 8 3 4 2 5 6 7]
 [8 5 9 7 6 1 4 2 3]
 [4 2 6 8 5 3 7 9 1]
 [7 1 3 9 2 4 8 5 6]
 [9 6 1 5 3 7 2 8 4]
 [2 8 7 4 1 9 6 3 5]
 [3 4 5 2 8 6 1 7 9]]


In [0]:
grid = [
        [7,8,0,0,0,3,0,0,0],
        [0,0,1,8,0,0,0,0,3],
        [0,3,0,4,0,0,0,5,0],
        [0,0,0,0,4,0,8,0,0],
        [2,1,0,5,0,0,0,9,0],
        [0,7,0,0,0,9,0,0,1],
        [0,0,7,0,9,0,4,0,0],
        [0,0,0,0,0,8,6,0,0],
        [6,0,0,0,2,0,0,8,0]
        ]

In [222]:
solve()
print(np.matrix(grid))

[[7 8 5 9 6 3 1 2 4]
 [4 2 1 8 7 5 9 6 3]
 [9 3 6 4 1 2 7 5 8]
 [3 6 9 2 4 1 8 7 5]
 [2 1 4 5 8 7 3 9 6]
 [5 7 8 6 3 9 2 4 1]
 [8 5 7 3 9 6 4 1 2]
 [1 4 2 7 5 8 6 3 9]
 [6 9 3 1 2 4 5 8 7]]


In [223]:
grid = [
        [0,0,0,0,0,0,0,0,0],
        [0,0,0,0,0,0,0,0,0],
        [0,0,0,0,0,0,0,0,0],
        [0,0,0,0,0,0,0,0,0],
        [0,0,0,0,0,0,0,0,0],
        [0,0,0,0,0,0,0,0,0],
        [0,0,0,0,0,0,0,0,0],
        [0,0,0,0,0,0,0,0,0],
        [0,0,0,0,0,0,0,0,0]
        ]
solve()
print(np.matrix(grid))

[[1 2 3 4 5 6 7 8 9]
 [4 5 6 7 8 9 1 2 3]
 [7 8 9 1 2 3 4 5 6]
 [2 1 4 3 6 5 8 9 7]
 [3 6 5 8 9 7 2 1 4]
 [8 9 7 2 1 4 3 6 5]
 [5 3 1 6 4 2 9 7 8]
 [6 4 2 9 7 8 5 3 1]
 [9 7 8 5 3 1 6 4 2]]
